bdk/bdk/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls', namespace='order')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
    ]

bdk/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('shoes1/', views.shoes1, name='shoes1'),
    path('shoes2/', views.shoes2, name='shoes2'),
    path('shoes3/', views.shoes3, name='shoes3'), 
    path('s11/', views.s11, name='s11'), 
    path('s12/', views.s12, name='s12'), 
    path('s21/', views.s21, name='s21'), 
    path('s22/', views.s22, name='s22'), 
    path('s31/', views.s31, name='s31'), 
    path('s32/', views.s32, name='s32'), 
    path('form/', views.form, name='form'), 
] 

bdk/order/urls.py
from django.urls import path
from order import views


app_name = 'order'
urlpatterns = [
    path('order', views.Order, name='order'),
] 

bdk/order/models.py
from django.db import models

# Create your models here.
class Order(models.Model):
    name1=models.CharField(max_length=128)
    name2=models.CharField(max_length=128)
    country=models.CharField(max_length=128)
    PT=models.CharField(max_length=128)
    ADR=models.CharField(max_length=128)
    phone=models.CharField(max_length=128)
    number=models.CharField(max_length=128)
    email=models.CharField(max_length=128)
    shoes=models.CharField(max_length=128)
    SD=models.CharField(max_length=128)

    def __str__(self):
        return self.name1

bdk/order/forms.py
from django import forms
from order.models import Order
from random import choice


class OrderForm(forms.ModelForm):
    name1=forms.CharField(
    label="姓氏",
    widget=forms.TextInput()
    )
    name2=forms.CharField(
    label="名字",
    widget=forms.TextInput()
    )
    country=forms.ChoiceField(  
    choices=(('台灣','台灣'),('香港','香港'),('澳門','澳門')),  
    label="國家/地區",
    widget=forms.Select()
    )
    PT=forms.CharField(
    label="郵遞區號",
    widget=forms.TextInput()
    )
    ADR=forms.CharField(
    label="地址",
    widget=forms.TextInput()
    )
    phone=forms.CharField(
    label="電話",
    widget=forms.TextInput()
    )
    number=forms.CharField(
    label="身份證字號",
    widget=forms.TextInput()
    )
    email=forms.CharField(
    label="電子郵件",
    widget=forms.TextInput()
    )
    shoes=forms.ChoiceField(  
        choices=(('New Balance MHANZSM1NT','New Balance MHANZSM1NT'),
                 ('ThreadborneFortis 3RC 2NT','ThreadborneFortis 3RC 2NT'),
                 ('NikeLeBron 16NT1','NikeLeBron 16NT1'),
                 ('AdidasHARDEN VOL. 3','AdidasHARDEN VOL. 3'),
                 ('Converse One Star MC18','Converse One Star MC18'),
                 ('VansChima Pro 2','VansChima Pro 2')),  
        label="鞋子種類",
        widget=forms.Select()
    )
    SD=forms.fields.ChoiceField(
        choices=(('標準','標準'),
                 ('快遞','快遞')),
        label='選擇寄送方式',
        widget=forms.widgets.RadioSelect
    )

    class Meta:
        model = Order
        fields = ['name1','name2','country','PT','ADR','phone','number','email','shoes','SD']
        
        
        
        
        
        
        
        

bdk/main/views.py
from django.shortcuts import render

def main(request):
    '''
    Render the main page
    '''
   
    return render(request, 'main/main.html')
def shoes1(request):
    '''
    Render the about page
    '''
    return render(request, 'main/shoes1.html')
def shoes2(request):
    '''
    Render the about page
    '''
    return render(request, 'main/shoes2.html')
def shoes3(request):
    '''
    Render the about page
    '''
    return render(request, 'main/shoes3.html')
def s11(request):
    '''
    Render the about page
    '''
    return render(request, 'main/s11.html')
def s12(request):
    '''
    Render the about page
    '''
    return render(request, 'main/s12.html')

def s21(request):
    '''
    Render the about page
    '''
    return render(request, 'main/s21.html')

def s22(request):
    '''
    Render the about page
    '''
    return render(request, 'main/s22.html')

def s31(request):
    '''
    Render the about page
    '''
    return render(request, 'main/s31.html')

def s32(request):
    '''
    Render the about page
    '''
    return render(request, 'main/s32.html')
def form(request):
    '''
    Render the about page
    '''
    return render(request, 'main/form.html')

 



    

bdk/order/views.py
from django.shortcuts import render
from order.forms import OrderForm



def Order(request):
    '''
    Render the order page
    '''
    template='order/order.html'
    if request.method =='GET':
        return render(request, template,{'orderForm':OrderForm()})
    
    
    orderForm = OrderForm(request.POST)
    if not orderForm.is_valid():
        return render(request, template, {'orderForm':OrderForm})
    orderForm.save()
    return render(request, 'main/main.html')

bdk/main/templates/main/s11.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/st.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>慢&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;跑&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><img class="s1" src="/static/main/img/NB.jpeg"></td>
    <td class="c1" >
      • HANZO 競賽跑鞋，S 系列，由日本設計美國研發製造。
      <br>• FANTOM FUZE 輕量化編織鞋面，中底部分後腳掌使用RevLite (落地緩震)前腳掌使用Rapid Rebound(推蹬回彈) 雙避震系統中底，前掌大底配置Dynaride系統，加強抓地力。
      
    </td>

  </tr>
  <tr>
    <td class="text1">尺寸<br>US 9<br>US 9.5<br>US 10<br>US 10.5</td>
  </tr>
  <tr>
    <td></td>
    <td>
    <ul>
    <li id="text2"><a class="c2" href="{% url 'order:order' %}">訂&nbsp;&nbsp;&nbsp;購</a></li>
    </ul>
    </td> 
      
  </tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  
  </div>
  <footer id="top">

  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/s12.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/st.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>慢&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;跑&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><img class="s1" src="/static/main/img/UA1.png"></td>
    <td class="c1" >
      • Threadborne鞋面緊致貼合、通風透氣，有助於提升動作的靈活性。<br>
      • 注塑Charged Cushioning鞋墊貼合腳掌，有助於提供量身定制般的舒適腳感。<br>
      • 雙層Charged Cushioning中底利用壓縮發泡材料，彈力與耐用度良好，有助於有效緩震與反彈。<br>
      • 刺繡設計豐富構造，緊鎖中足，有助於強化支撐性。<br>
      • 輕質網眼布鞋面有助於改善透氣性與舒適度。<br>
      • 足踝處的內靴設計包裹性良好，有助於改善舒適度與支撐性。<br>
      • 飾有多地形牽引花紋的外底有助於在不同類型的地面中提供良好的抓地力。<br>
      • 根據足底構造排布的彎曲凹槽，有助於改善關鍵部位的靈活度。
    
    </td>

  </tr>
  <tr>
    <td class="text1">尺寸<br>US 9<br>US 9.5<br>US 10<br>US 10.5</td>
  </tr>
  <tr>
    <td></td>
    <td>
    <ul>
    <li id="text2"><a class="c2" href="{% url 'order:order' %}">訂&nbsp;&nbsp;&nbsp;購</a></li>
    </ul>
    </td> 
  </tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  
  
  </ul> 
  
  </div>
  <footer id="top">
  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/s21.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/st.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>籃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;球&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><img class="s1" src="/static/main/img/nike.jpg"></td>
    <td class="c1" >
      LeBron 16 鞋款兼顧支撐力、衝擊緩震、即時靈敏度等強大機能，專為全球強悍絕倫的球員而設計。鞋舌和鞋帶的設計方便著用和自行調整貼合度，可在有需要時加強穩定足部；但如果想寬鬆自在地穿著，當然也沒問題。
    </td>

  </tr>
  <tr>
    <td class="text1">尺寸<br>US 9<br>US 9.5<br>US 10<br>US 10.5</td>
  </tr>
  <tr>
    <td></td>
    <td>
    <ul>
    <li id="text2"><a class="c2" href="{% url 'order:order' %}">訂&nbsp;&nbsp;&nbsp;購</a></li>
    </ul>
    </td> 
  </tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  <footer id="top">
  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/s22.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/st.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>籃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;球&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><img class="s1" src="/static/main/img/adidas.jpg"></td>
    <td class="c1" >
      HARDEN VOL.3 靈感來自詹姆斯哈登，鞋子的設計是為了創造防守者的空間，並在每次用他的獨特性風格控球時操縱球場。 當你用交叉和後背攻擊籃框時，它們的設計更靈活，可以進行側向移動和控制。 在每個歐洲步驟上回歸能量，它們具有出色的抓地力和控制力，可以改變方向。
    </td>

  </tr>
  <tr>
    <td class="text1">尺寸<br>US 9<br>US 9.5<br>US 10<br>US 10.5</td>
  </tr>
  <tr>
    <td></td>
    <td>
    <ul>
    <li id="text2"><a class="c2" href="{% url 'order:order' %}">訂&nbsp;&nbsp;&nbsp;購</a></li>
    </ul>
    </td> 
  </tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  <footer id="top">
  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/s31.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/st.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>帆&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;布&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><img class="s1" src="/static/main/img/Converse .png"></td>
    <td class="c1" >
      • GORE-TEX® 的內襯和防潑水鞋面<br>
      • 提供柔軟舒適的穿著體驗<br>
      • 街頭美學與機能風格融為一體<br>
      • 打造具備戶外機能的全新潮流鞋款
    </td>

  </tr>
  <tr>
    <td class="text1">尺寸<br>US 9<br>US 9.5<br>US 10<br>US 10.5</td>
  </tr>
  <tr>
    <td></td>
    <td>
    <ul>
    <li id="text2"><a class="c2" href="{% url 'order:order' %}">訂&nbsp;&nbsp;&nbsp;購</a></li>
    </ul>
    </td> 
  </tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  <footer id="top">
  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/s32.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/st.css' %}">
</head>
<body>

<div id="wrapper">
  <aside>
  <b><I><h1>帆&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;布&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><img class="s1" src="/static/main/img/Vans.jpg"></td>
    <td class="c1" >
      Vans Pro Lite 輕便職業滑板鞋款在鞋面細節處採用了 Duracap 加固耐磨材質，同時通過進化版鞋邊條增加了整體的靈活和耐磨性能，加上 Vans 全新 UltraCush Lite 3D 鞋墊， Chima Pro 2 可以說是專為高強度的滑板運動而設計的。UltraCush 鞋墊由一體式的護踵模型包裹雙重密度的泡沫材質，在保持輕便的同時保證了靈活的腳感，Chima Pro 2 提供了多方位的緩震及板上體驗，可以支持各種不同形式的滑板地形 —— 無論是台子、斜坡、弧面、碗池，亦或是馬路牙子、樓梯扶手和滑板公園。同樣的如果你要完成 slappies、外轉翻板、各種「呲」或是大型騰空動作，無論是想在哪裡落地，穿上它你都可以像 Chima 那樣滑板！
    </td>

  </tr>
  <tr>
    <td class="text1">尺寸<br>US 9<br>US 9.5<br>US 10<br>US 10.5</td>
  </tr>
  <tr>
    <td></td>
    <td>
    <ul>
    <li id="text2"><a class="c2" href="{% url 'order:order' %}">訂&nbsp;&nbsp;&nbsp;購</a></li>
    </ul>
    </td> 
  </tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  
  <footer id="top">
  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/shoes1.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/shoes1.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>慢&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;跑&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
<table>
  <tr>
  <td><a href="{% url 'main:s11' %}"><img class="s1" src="/static/main/img/NB.jpeg"></a></td>
  <td><a href="{% url 'main:s12' %}"><img class="s1" src="/static/main/img/UA1.png"></a></td>
</tr>
</table>
<table>
<tr>
  <td class="text1"><br><br>New Balance<br>MHANZSM1NT<br><br>NT $ 4,850</td>
  <td class="text1"><br><br>Threadborne Fortis 3<br>RC 2NT<br><br>NT $ 4,380</td>
</tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  <footer id="top">

  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 

</body>
</html>

bdk/main/templates/main/shoes2.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-慢跑鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/shoes2.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>籃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;球&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
  <table>
  <tr>
  <td><a href="{% url 'main:s21' %}"><img class="s2" src="/static/main/img/nike.jpg"></a></td>
  <td><a href="{% url 'main:s22' %}"><img class="s2" src="/static/main/img/adidas.jpg"></a></td>
</tr>
</table>
<table>
<tr>
  <td class="text2"><br><br>Nike LeBron 16NT1<br><br>NT $ 6,600</td>
  <td class="text2"><br><br>Adidas HARDEN VOL. 3<br><br>NT $ 5,590</td>
</tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  <footer id="top">

  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 
</body>
</html>

bdk/main/templates/main/shoes3.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>BDK鞋鋪-帆布鞋</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/shoes3.css' %}">
</head>
<body>
<div id="wrapper">
  <aside>
  <b><I><h1>帆&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;布&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鞋</h1></I></b>
  <table>
  <tr>
  <td><a href="{% url 'main:s31' %}"><img class="s3" src="/static/main/img/Converse .png"></a></td>
  <td><a href="{% url 'main:s32' %}"><img class="s3" src="/static/main/img/Vans.jpg"></a></td>
</tr>
</table>
<table>
<tr>
  <td class="text3"><br><br>Converse One Star <br>MC18<br><br>NT $ 3,980</td>
  <td class="text3"><br><br>Vans Chima Pro 2<br><br>NT $ 2,980</td>
</tr>
</table>
  </aside>
  <div id="content">
  <ul id="menu">
  <li id="one"><a class="tt" href="{% url 'main:main' %}">B.D.K 鞋鋪</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
 
  <li><a class="tt" href="{% url 'main:shoes1' %}">慢跑鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <li><a class="tt" href="{% url 'main:shoes2' %}">籃球鞋</a></li>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
 
  <li><a class="tt" href="{% url 'main:shoes3' %}">帆布鞋</a></li>
  </ul>
  </div>
  <footer id="top">
  
  </footer>
  <footer id="under">
  公司地址：台中市霧峰區吉峰東路148號
  <br>
  公司電話：08-0009000
  </footer>
  
</div> 
</body>
</html>